// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbortMultipartUpload(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AbortMultipartUpload'](arg1, arg2, arg3, arg4);
}

export function ActiveAccount() {
  return window['go']['app']['App']['ActiveAccount']();
}

export function BatchDeleteObjects(arg1, arg2, arg3) {
  return window['go']['app']['App']['BatchDeleteObjects'](arg1, arg2, arg3);
}

export function BatchUpdateObjectAttributes(arg1, arg2) {
  return window['go']['app']['App']['BatchUpdateObjectAttributes'](arg1, arg2);
}

export function BucketLocation(arg1, arg2) {
  return window['go']['app']['App']['BucketLocation'](arg1, arg2);
}

export function CancelTransferTask(arg1) {
  return window['go']['app']['App']['CancelTransferTask'](arg1);
}

export function CheckForUpdates(arg1) {
  return window['go']['app']['App']['CheckForUpdates'](arg1);
}

export function ClearCompletedTransfers() {
  return window['go']['app']['App']['ClearCompletedTransfers']();
}

export function CompleteMultipartUpload(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['CompleteMultipartUpload'](arg1, arg2, arg3, arg4, arg5);
}

export function CopyObject(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['CopyObject'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateAccount(arg1) {
  return window['go']['app']['App']['CreateAccount'](arg1);
}

export function CreateAppBackup(arg1, arg2) {
  return window['go']['app']['App']['CreateAppBackup'](arg1, arg2);
}

export function CreateBucket(arg1, arg2) {
  return window['go']['app']['App']['CreateBucket'](arg1, arg2);
}

export function CreateBucketSnapshot(arg1, arg2) {
  return window['go']['app']['App']['CreateBucketSnapshot'](arg1, arg2);
}

export function CreateFolder(arg1, arg2, arg3) {
  return window['go']['app']['App']['CreateFolder'](arg1, arg2, arg3);
}

export function CreateSymlink(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['CreateSymlink'](arg1, arg2, arg3, arg4);
}

export function DeleteAccount(arg1) {
  return window['go']['app']['App']['DeleteAccount'](arg1);
}

export function DeleteBucket(arg1, arg2) {
  return window['go']['app']['App']['DeleteBucket'](arg1, arg2);
}

export function DeleteBucketCORS(arg1, arg2) {
  return window['go']['app']['App']['DeleteBucketCORS'](arg1, arg2);
}

export function DeleteBucketEncryption(arg1, arg2) {
  return window['go']['app']['App']['DeleteBucketEncryption'](arg1, arg2);
}

export function DeleteBucketLifecycle(arg1, arg2) {
  return window['go']['app']['App']['DeleteBucketLifecycle'](arg1, arg2);
}

export function DeleteBucketPolicy(arg1, arg2) {
  return window['go']['app']['App']['DeleteBucketPolicy'](arg1, arg2);
}

export function DeleteBucketSnapshot(arg1) {
  return window['go']['app']['App']['DeleteBucketSnapshot'](arg1);
}

export function DeleteBucketWebsite(arg1, arg2) {
  return window['go']['app']['App']['DeleteBucketWebsite'](arg1, arg2);
}

export function DeleteObject(arg1, arg2, arg3) {
  return window['go']['app']['App']['DeleteObject'](arg1, arg2, arg3);
}

export function DeleteObjectWithOptions(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['DeleteObjectWithOptions'](arg1, arg2, arg3, arg4);
}

export function DeleteSavedSearchQuery(arg1) {
  return window['go']['app']['App']['DeleteSavedSearchQuery'](arg1);
}

export function DeleteTransferTask(arg1) {
  return window['go']['app']['App']['DeleteTransferTask'](arg1);
}

export function DisableBucketMAZ(arg1, arg2) {
  return window['go']['app']['App']['DisableBucketMAZ'](arg1, arg2);
}

export function DownloadBatch(arg1, arg2) {
  return window['go']['app']['App']['DownloadBatch'](arg1, arg2);
}

export function DownloadImportTemplate(arg1) {
  return window['go']['app']['App']['DownloadImportTemplate'](arg1);
}

export function DownloadObject(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['DownloadObject'](arg1, arg2, arg3, arg4);
}

export function DownloadObjectWithOptions(arg1, arg2) {
  return window['go']['app']['App']['DownloadObjectWithOptions'](arg1, arg2);
}

export function EnableBucketMAZ(arg1, arg2) {
  return window['go']['app']['App']['EnableBucketMAZ'](arg1, arg2);
}

export function EnableBucketVersioning(arg1, arg2) {
  return window['go']['app']['App']['EnableBucketVersioning'](arg1, arg2);
}

export function ExportAccounts() {
  return window['go']['app']['App']['ExportAccounts']();
}

export function ExportSearchResults(arg1, arg2, arg3) {
  return window['go']['app']['App']['ExportSearchResults'](arg1, arg2, arg3);
}

export function ForceQuit() {
  return window['go']['app']['App']['ForceQuit']();
}

export function GenerateAccessLinks(arg1, arg2) {
  return window['go']['app']['App']['GenerateAccessLinks'](arg1, arg2);
}

export function GetBucketACL(arg1, arg2) {
  return window['go']['app']['App']['GetBucketACL'](arg1, arg2);
}

export function GetBucketCORS(arg1, arg2) {
  return window['go']['app']['App']['GetBucketCORS'](arg1, arg2);
}

export function GetBucketEncryption(arg1, arg2) {
  return window['go']['app']['App']['GetBucketEncryption'](arg1, arg2);
}

export function GetBucketLifecycle(arg1, arg2) {
  return window['go']['app']['App']['GetBucketLifecycle'](arg1, arg2);
}

export function GetBucketMAZConfig(arg1, arg2) {
  return window['go']['app']['App']['GetBucketMAZConfig'](arg1, arg2);
}

export function GetBucketPolicy(arg1, arg2) {
  return window['go']['app']['App']['GetBucketPolicy'](arg1, arg2);
}

export function GetBucketReferer(arg1, arg2) {
  return window['go']['app']['App']['GetBucketReferer'](arg1, arg2);
}

export function GetBucketVersioning(arg1, arg2) {
  return window['go']['app']['App']['GetBucketVersioning'](arg1, arg2);
}

export function GetBucketWebsite(arg1, arg2) {
  return window['go']['app']['App']['GetBucketWebsite'](arg1, arg2);
}

export function GetDefaultDownloadDir() {
  return window['go']['app']['App']['GetDefaultDownloadDir']();
}

export function GetObjectAttributes(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetObjectAttributes'](arg1, arg2, arg3);
}

export function GetObjectLegalHold(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['GetObjectLegalHold'](arg1, arg2, arg3, arg4);
}

export function GetObjectLockConfiguration(arg1, arg2) {
  return window['go']['app']['App']['GetObjectLockConfiguration'](arg1, arg2);
}

export function GetObjectRetention(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['GetObjectRetention'](arg1, arg2, arg3, arg4);
}

export function GetPresignedDownloadURL(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['GetPresignedDownloadURL'](arg1, arg2, arg3, arg4);
}

export function GetPresignedDownloadURLWithHeaders(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['GetPresignedDownloadURLWithHeaders'](arg1, arg2, arg3, arg4, arg5);
}

export function GetPresignedUploadURL(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['GetPresignedUploadURL'](arg1, arg2, arg3, arg4);
}

export function GetProviderCapabilities(arg1) {
  return window['go']['app']['App']['GetProviderCapabilities'](arg1);
}

export function GetPublicAccessBlock(arg1, arg2) {
  return window['go']['app']['App']['GetPublicAccessBlock'](arg1, arg2);
}

export function GetSymlink(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetSymlink'](arg1, arg2, arg3);
}

export function GetSystemMetrics() {
  return window['go']['app']['App']['GetSystemMetrics']();
}

export function GetTransferConfig() {
  return window['go']['app']['App']['GetTransferConfig']();
}

export function GetTransferSpeedLimit() {
  return window['go']['app']['App']['GetTransferSpeedLimit']();
}

export function HasProviderCapability(arg1, arg2) {
  return window['go']['app']['App']['HasProviderCapability'](arg1, arg2);
}

export function HeadBucket(arg1, arg2) {
  return window['go']['app']['App']['HeadBucket'](arg1, arg2);
}

export function HeadObject(arg1, arg2, arg3) {
  return window['go']['app']['App']['HeadObject'](arg1, arg2, arg3);
}

export function ImportAccounts() {
  return window['go']['app']['App']['ImportAccounts']();
}

export function ImportAccountsBatch() {
  return window['go']['app']['App']['ImportAccountsBatch']();
}

export function InitiateMultipartUpload(arg1, arg2, arg3) {
  return window['go']['app']['App']['InitiateMultipartUpload'](arg1, arg2, arg3);
}

export function ListAccounts() {
  return window['go']['app']['App']['ListAccounts']();
}

export function ListBucketSnapshots(arg1, arg2) {
  return window['go']['app']['App']['ListBucketSnapshots'](arg1, arg2);
}

export function ListBuckets(arg1) {
  return window['go']['app']['App']['ListBuckets'](arg1);
}

export function ListObjects(arg1, arg2) {
  return window['go']['app']['App']['ListObjects'](arg1, arg2);
}

export function ListSavedSearchQueries() {
  return window['go']['app']['App']['ListSavedSearchQueries']();
}

export function ListTransferTasks() {
  return window['go']['app']['App']['ListTransferTasks']();
}

export function ListTransferTasksPaged(arg1) {
  return window['go']['app']['App']['ListTransferTasksPaged'](arg1);
}

export function MoveObjects(arg1, arg2) {
  return window['go']['app']['App']['MoveObjects'](arg1, arg2);
}

export function MoveObjectsWithOptions(arg1, arg2, arg3) {
  return window['go']['app']['App']['MoveObjectsWithOptions'](arg1, arg2, arg3);
}

export function OnSecondInstance(arg1) {
  return window['go']['app']['App']['OnSecondInstance'](arg1);
}

export function OpenDirectoryDialogWithFiles(arg1) {
  return window['go']['app']['App']['OpenDirectoryDialogWithFiles'](arg1);
}

export function OpenFileDialog(arg1, arg2) {
  return window['go']['app']['App']['OpenFileDialog'](arg1, arg2);
}

export function OpenMultipleFilesDialog(arg1, arg2) {
  return window['go']['app']['App']['OpenMultipleFilesDialog'](arg1, arg2);
}

export function PauseTransferTask(arg1) {
  return window['go']['app']['App']['PauseTransferTask'](arg1);
}

export function PingEndpoint(arg1, arg2) {
  return window['go']['app']['App']['PingEndpoint'](arg1, arg2);
}

export function ProviderCapabilities() {
  return window['go']['app']['App']['ProviderCapabilities']();
}

export function RenameObject(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['RenameObject'](arg1, arg2, arg3, arg4);
}

export function RenameObjectWithOptions(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['RenameObjectWithOptions'](arg1, arg2, arg3, arg4, arg5);
}

export function RestoreAppBackup(arg1) {
  return window['go']['app']['App']['RestoreAppBackup'](arg1);
}

export function ResumeTransferTask(arg1) {
  return window['go']['app']['App']['ResumeTransferTask'](arg1);
}

export function SaveFileDialog(arg1, arg2, arg3) {
  return window['go']['app']['App']['SaveFileDialog'](arg1, arg2, arg3);
}

export function SaveSearchQuery(arg1, arg2) {
  return window['go']['app']['App']['SaveSearchQuery'](arg1, arg2);
}

export function SearchObjects(arg1, arg2) {
  return window['go']['app']['App']['SearchObjects'](arg1, arg2);
}

export function SelectLocalFolder(arg1) {
  return window['go']['app']['App']['SelectLocalFolder'](arg1);
}

export function SetActiveAccount(arg1) {
  return window['go']['app']['App']['SetActiveAccount'](arg1);
}

export function SetBucketACL(arg1, arg2, arg3) {
  return window['go']['app']['App']['SetBucketACL'](arg1, arg2, arg3);
}

export function SetBucketCORS(arg1, arg2, arg3) {
  return window['go']['app']['App']['SetBucketCORS'](arg1, arg2, arg3);
}

export function SetBucketEncryption(arg1, arg2, arg3) {
  return window['go']['app']['App']['SetBucketEncryption'](arg1, arg2, arg3);
}

export function SetBucketLifecycle(arg1, arg2, arg3) {
  return window['go']['app']['App']['SetBucketLifecycle'](arg1, arg2, arg3);
}

export function SetBucketPolicy(arg1, arg2, arg3) {
  return window['go']['app']['App']['SetBucketPolicy'](arg1, arg2, arg3);
}

export function SetBucketReferer(arg1, arg2, arg3) {
  return window['go']['app']['App']['SetBucketReferer'](arg1, arg2, arg3);
}

export function SetBucketWebsite(arg1, arg2, arg3) {
  return window['go']['app']['App']['SetBucketWebsite'](arg1, arg2, arg3);
}

export function SetPublicAccessBlock(arg1, arg2, arg3) {
  return window['go']['app']['App']['SetPublicAccessBlock'](arg1, arg2, arg3);
}

export function SetTransferConcurrency(arg1) {
  return window['go']['app']['App']['SetTransferConcurrency'](arg1);
}

export function SetTransferSpeedLimit(arg1) {
  return window['go']['app']['App']['SetTransferSpeedLimit'](arg1);
}

export function ShowPathInFileManager(arg1) {
  return window['go']['app']['App']['ShowPathInFileManager'](arg1);
}

export function SupportedProviders() {
  return window['go']['app']['App']['SupportedProviders']();
}

export function SuspendBucketVersioning(arg1, arg2) {
  return window['go']['app']['App']['SuspendBucketVersioning'](arg1, arg2);
}

export function TestAccountConnection(arg1) {
  return window['go']['app']['App']['TestAccountConnection'](arg1);
}

export function TestAccountConnectionPreview(arg1) {
  return window['go']['app']['App']['TestAccountConnectionPreview'](arg1);
}

export function UpdateAccount(arg1, arg2) {
  return window['go']['app']['App']['UpdateAccount'](arg1, arg2);
}

export function UpdateObjectAttributes(arg1, arg2) {
  return window['go']['app']['App']['UpdateObjectAttributes'](arg1, arg2);
}

export function UpdateObjectLegalHold(arg1, arg2) {
  return window['go']['app']['App']['UpdateObjectLegalHold'](arg1, arg2);
}

export function UpdateObjectRetention(arg1, arg2) {
  return window['go']['app']['App']['UpdateObjectRetention'](arg1, arg2);
}

export function UpdateSavedSearchQuery(arg1, arg2, arg3) {
  return window['go']['app']['App']['UpdateSavedSearchQuery'](arg1, arg2, arg3);
}

export function UploadFilesFromPaths(arg1) {
  return window['go']['app']['App']['UploadFilesFromPaths'](arg1);
}

export function UploadObject(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['UploadObject'](arg1, arg2, arg3, arg4);
}

export function UploadPart(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['UploadPart'](arg1, arg2, arg3, arg4, arg5, arg6);
}
