// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {accounts} from '../models';
import {objects} from '../models';
import {system} from '../models';
import {backup} from '../models';
import {buckets} from '../models';
import {transfer} from '../models';
import {search} from '../models';
import {config} from '../models';
import {options} from '../models';
import {app} from '../models';
import {types} from '../models';

export function AbortMultipartUpload(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function ActiveAccount():Promise<accounts.Account>;

export function BatchDeleteObjects(arg1:string,arg2:string,arg3:Array<string>):Promise<objects.BatchDeleteResult>;

export function BatchUpdateObjectAttributes(arg1:string,arg2:Array<objects.ObjectAttributesPatch>):Promise<objects.BatchAttributesResult>;

export function BucketLocation(arg1:string,arg2:string):Promise<string>;

export function CancelTransferTask(arg1:string):Promise<void>;

export function CheckForUpdates(arg1:string):Promise<system.UpdateInfo>;

export function CompleteMultipartUpload(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Record<number, string>):Promise<void>;

export function CopyObject(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function CreateAccount(arg1:accounts.CreateAccountInput):Promise<accounts.Account>;

export function CreateAppBackup(arg1:boolean,arg2:string):Promise<backup.BackupHeader>;

export function CreateBucket(arg1:string,arg2:buckets.CreateBucketInput):Promise<void>;

export function CreateBucketSnapshot(arg1:string,arg2:string):Promise<backup.BackupHeader>;

export function CreateFolder(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CreateSymlink(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DeleteAccessLinkHistory(arg1:string,arg2:string):Promise<void>;

export function DeleteAccount(arg1:string):Promise<void>;

export function DeleteBucket(arg1:string,arg2:string):Promise<void>;

export function DeleteBucketCORS(arg1:string,arg2:string):Promise<void>;

export function DeleteBucketEncryption(arg1:string,arg2:string):Promise<void>;

export function DeleteBucketLifecycle(arg1:string,arg2:string):Promise<void>;

export function DeleteBucketPolicy(arg1:string,arg2:string):Promise<void>;

export function DeleteBucketSnapshot(arg1:string):Promise<void>;

export function DeleteBucketWebsite(arg1:string,arg2:string):Promise<void>;

export function DeleteObject(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteObjectWithOptions(arg1:string,arg2:string,arg3:string,arg4:objects.MutationOptions):Promise<void>;

export function DeleteSavedSearchQuery(arg1:string):Promise<void>;

export function DownloadBatch(arg1:string,arg2:objects.DownloadBatchInput):Promise<transfer.TransferTask>;

export function DownloadObject(arg1:string,arg2:string,arg3:string,arg4:string):Promise<transfer.TransferTask>;

export function DownloadObjectWithOptions(arg1:string,arg2:objects.DownloadObjectInput):Promise<transfer.TransferTask>;

export function EnableBucketVersioning(arg1:string,arg2:string):Promise<void>;

export function ExportAccounts():Promise<accounts.ExportSummary>;

export function ExportSearchResults(arg1:string,arg2:search.SearchQuery,arg3:string):Promise<Array<number>>;

export function ForceQuit():Promise<void>;

export function GenerateAccessLinks(arg1:string,arg2:objects.AccessLinkRequest):Promise<Array<objects.AccessLink>>;

export function GetBucketACL(arg1:string,arg2:string):Promise<config.BucketACL>;

export function GetBucketCORS(arg1:string,arg2:string):Promise<config.BucketCORS>;

export function GetBucketEncryption(arg1:string,arg2:string):Promise<config.BucketEncryption>;

export function GetBucketLifecycle(arg1:string,arg2:string):Promise<Array<config.LifecycleRule>>;

export function GetBucketPolicy(arg1:string,arg2:string):Promise<config.BucketPolicy>;

export function GetBucketReferer(arg1:string,arg2:string):Promise<config.BucketReferer>;

export function GetBucketVersioning(arg1:string,arg2:string):Promise<config.BucketVersioning>;

export function GetBucketWebsite(arg1:string,arg2:string):Promise<config.BucketWebsite>;

export function GetObjectAttributes(arg1:string,arg2:string,arg3:string):Promise<objects.ObjectAttributes>;

export function GetObjectLegalHold(arg1:string,arg2:string,arg3:string,arg4:string):Promise<objects.ObjectLegalHoldState>;

export function GetObjectLockConfiguration(arg1:string,arg2:string):Promise<objects.ObjectLockConfiguration>;

export function GetObjectRetention(arg1:string,arg2:string,arg3:string,arg4:string):Promise<objects.ObjectRetentionState>;

export function GetPresignedDownloadURL(arg1:string,arg2:string,arg3:string,arg4:number):Promise<string>;

export function GetPresignedDownloadURLWithHeaders(arg1:string,arg2:string,arg3:string,arg4:number,arg5:Record<string, string>):Promise<string>;

export function GetPresignedUploadURL(arg1:string,arg2:string,arg3:string,arg4:number):Promise<string>;

export function GetPublicAccessBlock(arg1:string,arg2:string):Promise<config.PublicAccessBlock>;

export function GetSystemMetrics():Promise<system.SystemMetrics>;

export function GetTransferSpeedLimit():Promise<number>;

export function HeadBucket(arg1:string,arg2:string):Promise<void>;

export function HeadObject(arg1:string,arg2:string,arg3:string):Promise<objects.ObjectInfo>;

export function ImportAccounts():Promise<accounts.ImportSummary>;

export function InitiateMultipartUpload(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ListAccessLinkHistory(arg1:string,arg2:number):Promise<Array<objects.LinkHistoryEntry>>;

export function ListAccounts():Promise<Array<accounts.Account>>;

export function ListBucketSnapshots(arg1:string,arg2:string):Promise<Array<backup.BackupHeader>>;

export function ListBuckets(arg1:string):Promise<Array<buckets.BucketInfo>>;

export function ListObjects(arg1:string,arg2:objects.ListObjectsInput):Promise<objects.ListObjectsResult>;

export function ListSavedSearchQueries():Promise<Array<search.SavedQuery>>;

export function ListTransferTasks():Promise<Array<transfer.TransferTask>>;

export function MoveObjects(arg1:string,arg2:Array<objects.MoveObjectRequest>):Promise<objects.MoveObjectsResult>;

export function MoveObjectsWithOptions(arg1:string,arg2:Array<objects.MoveObjectRequest>,arg3:objects.MutationOptions):Promise<objects.MoveObjectsResult>;

export function OnSecondInstance(arg1:options.SecondInstanceData):Promise<void>;

export function OpenFileDialog(arg1:string,arg2:Array<app.FileFilter>):Promise<string>;

export function PauseTransferTask(arg1:string):Promise<void>;

export function PingEndpoint(arg1:string,arg2:number):Promise<system.PingResult>;

export function ProviderCapabilities():Promise<Array<types.ProviderCapability>>;

export function RenameObject(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function RenameObjectWithOptions(arg1:string,arg2:string,arg3:string,arg4:string,arg5:objects.MutationOptions):Promise<void>;

export function RestoreAppBackup():Promise<void>;

export function ResumeTransferTask(arg1:string):Promise<void>;

export function SaveFileDialog(arg1:string,arg2:string,arg3:Array<app.FileFilter>):Promise<string>;

export function SaveSearchQuery(arg1:string,arg2:search.SearchQuery):Promise<search.SavedQuery>;

export function SearchObjects(arg1:string,arg2:search.SearchQuery):Promise<search.SearchResponse>;

export function SelectLocalFolder(arg1:string):Promise<string>;

export function SetActiveAccount(arg1:string):Promise<accounts.Account>;

export function SetBucketACL(arg1:string,arg2:string,arg3:config.BucketACL):Promise<void>;

export function SetBucketCORS(arg1:string,arg2:string,arg3:config.BucketCORS):Promise<void>;

export function SetBucketEncryption(arg1:string,arg2:string,arg3:config.BucketEncryption):Promise<void>;

export function SetBucketLifecycle(arg1:string,arg2:string,arg3:Array<config.LifecycleRule>):Promise<void>;

export function SetBucketPolicy(arg1:string,arg2:string,arg3:config.BucketPolicy):Promise<void>;

export function SetBucketReferer(arg1:string,arg2:string,arg3:config.BucketReferer):Promise<void>;

export function SetBucketWebsite(arg1:string,arg2:string,arg3:config.BucketWebsite):Promise<void>;

export function SetPublicAccessBlock(arg1:string,arg2:string,arg3:config.PublicAccessBlock):Promise<void>;

export function SetTransferSpeedLimit(arg1:number):Promise<void>;

export function SupportedProviders():Promise<Array<types.ProviderMetadata>>;

export function SuspendBucketVersioning(arg1:string,arg2:string):Promise<void>;

export function TestAccountConnection(arg1:string):Promise<accounts.ConnectionTestResult>;

export function TestAccountConnectionPreview(arg1:accounts.CreateAccountInput):Promise<accounts.ConnectionTestResult>;

export function UpdateAccount(arg1:string,arg2:accounts.UpdateAccountInput):Promise<accounts.Account>;

export function UpdateObjectAttributes(arg1:string,arg2:objects.ObjectAttributesPatch):Promise<objects.ObjectAttributes>;

export function UpdateObjectLegalHold(arg1:string,arg2:objects.UpdateObjectLegalHoldInput):Promise<objects.ObjectLegalHoldState>;

export function UpdateObjectRetention(arg1:string,arg2:objects.UpdateObjectRetentionInput):Promise<objects.ObjectRetentionState>;

export function UpdateSavedSearchQuery(arg1:string,arg2:string,arg3:search.SearchQuery):Promise<search.SavedQuery>;

export function UploadObject(arg1:string,arg2:string,arg3:string,arg4:string):Promise<transfer.TransferTask>;

export function UploadPart(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:Array<number>):Promise<string>;
