// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {accounts} from '../models';
import {objects} from '../models';
import {system} from '../models';
import {storage} from '../models';
import {transfer} from '../models';
import {app} from '../models';
import {config} from '../models';
import {types} from '../models';
import {logger} from '../models';
import {options} from '../models';

export function AbortMultipartUpload(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function ActiveAccount():Promise<accounts.Account>;

export function BatchDeleteObjects(arg1:string,arg2:string,arg3:Array<string>):Promise<objects.BatchDeleteResult>;

export function BatchUpdateObjectAttributes(arg1:string,arg2:Array<objects.ObjectAttributesPatch>):Promise<objects.BatchAttributesResult>;

export function BucketLocation(arg1:string,arg2:string):Promise<string>;

export function CancelTransferTask(arg1:string):Promise<void>;

export function CheckForUpdates(arg1:string):Promise<system.UpdateInfo>;

export function ClearCompletedTransfers():Promise<number>;

export function CompleteMultipartUpload(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Record<number, string>):Promise<void>;

export function CopyObject(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function CreateAccount(arg1:accounts.CreateAccountInput):Promise<accounts.Account>;

export function CreateBucket(arg1:string,arg2:storage.BucketCreateInput):Promise<void>;

export function CreateFolder(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CreateSymlink(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DeleteAccount(arg1:string):Promise<void>;

export function DeleteBucket(arg1:string,arg2:string):Promise<void>;

export function DeleteBucketCORS(arg1:string,arg2:string):Promise<void>;

export function DeleteBucketEncryption(arg1:string,arg2:string):Promise<void>;

export function DeleteBucketLifecycle(arg1:string,arg2:string):Promise<void>;

export function DeleteBucketPolicy(arg1:string,arg2:string):Promise<void>;

export function DeleteBucketWebsite(arg1:string,arg2:string):Promise<void>;

export function DeleteObject(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteObjectWithOptions(arg1:string,arg2:string,arg3:string,arg4:objects.MutationOptions):Promise<void>;

export function DeleteTransferTask(arg1:string):Promise<void>;

export function Dial(arg1:string):Promise<accounts.DialResult>;

export function DialPreview(arg1:accounts.CreateAccountInput):Promise<accounts.DialResult>;

export function DisableBucketMAZ(arg1:string,arg2:string):Promise<void>;

export function DownloadBatch(arg1:string,arg2:objects.DownloadBatchInput):Promise<transfer.TransferTask>;

export function DownloadImportTemplate(arg1:string):Promise<void>;

export function DownloadObject(arg1:string,arg2:string,arg3:string,arg4:string):Promise<transfer.TransferTask>;

export function DownloadObjectWithOptions(arg1:string,arg2:objects.DownloadObjectInput):Promise<transfer.TransferTask>;

export function EnableBucketMAZ(arg1:string,arg2:string):Promise<void>;

export function EnableBucketVersioning(arg1:string,arg2:string):Promise<void>;

export function ExportAccounts():Promise<accounts.ExportSummary>;

export function ExportLogs(arg1:string):Promise<string>;

export function ForceQuit():Promise<void>;

export function GenerateAccessLinks(arg1:string,arg2:objects.AccessLinkRequest):Promise<Array<objects.AccessLink>>;

export function GetAccountCredentials(arg1:string):Promise<app.AccountCredentials>;

export function GetBucketACL(arg1:string,arg2:string):Promise<storage.BucketACL>;

export function GetBucketCORS(arg1:string,arg2:string):Promise<config.BucketCORS>;

export function GetBucketEncryption(arg1:string,arg2:string):Promise<config.BucketEncryption>;

export function GetBucketLifecycle(arg1:string,arg2:string):Promise<Array<config.LifecycleRule>>;

export function GetBucketMAZConfig(arg1:string,arg2:string):Promise<storage.MAZConfiguration>;

export function GetBucketPolicy(arg1:string,arg2:string):Promise<config.BucketPolicy>;

export function GetBucketReferer(arg1:string,arg2:string):Promise<storage.BucketReferer>;

export function GetBucketVersioning(arg1:string,arg2:string):Promise<storage.BucketVersioningConfiguration>;

export function GetBucketWebsite(arg1:string,arg2:string):Promise<config.BucketWebsite>;

export function GetDefaultDownloadDir():Promise<string>;

export function GetLogDirectory():Promise<string>;

export function GetLogLevel():Promise<string>;

export function GetObjectAttributes(arg1:string,arg2:string,arg3:string):Promise<objects.ObjectAttributes>;

export function GetObjectLegalHold(arg1:string,arg2:string,arg3:string,arg4:string):Promise<storage.ObjectLegalHoldState>;

export function GetObjectLockConfiguration(arg1:string,arg2:string):Promise<storage.ObjectLockConfiguration>;

export function GetObjectRetention(arg1:string,arg2:string,arg3:string,arg4:string):Promise<storage.ObjectRetentionState>;

export function GetPresignedDownloadURL(arg1:string,arg2:string,arg3:string,arg4:number):Promise<string>;

export function GetPresignedDownloadURLWithHeaders(arg1:string,arg2:string,arg3:string,arg4:number,arg5:Record<string, string>):Promise<string>;

export function GetPresignedUploadURL(arg1:string,arg2:string,arg3:string,arg4:number):Promise<string>;

export function GetProviderFeatures(arg1:string):Promise<Array<types.ProviderFeature>>;

export function GetPublicAccessBlock(arg1:string,arg2:string):Promise<storage.PublicAccessBlock>;

export function GetSymlink(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetTransferConfig():Promise<transfer.TransferConfig>;

export function GetTransferSpeedLimit():Promise<number>;

export function HasProviderFeature(arg1:string,arg2:string):Promise<boolean>;

export function HeadBucket(arg1:string,arg2:string):Promise<void>;

export function HeadObject(arg1:string,arg2:string,arg3:string):Promise<storage.ObjectDescriptor>;

export function ImportAccounts():Promise<accounts.ImportSummary>;

export function ImportAccountsBatch():Promise<accounts.BatchImportSummary>;

export function InitiateMultipartUpload(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ListAccounts():Promise<Array<accounts.Account>>;

export function ListBuckets(arg1:string):Promise<Array<storage.BucketDescriptor>>;

export function ListObjects(arg1:string,arg2:storage.ListObjectsInput):Promise<storage.ListObjectsResult>;

export function ListTransferTasks():Promise<Array<transfer.TransferTask>>;

export function ListTransferTasksPaged(arg1:app.ListTransferTasksInput):Promise<app.ListTransferTasksResult>;

export function LogBatch(arg1:Array<logger.LogEntry>):Promise<void>;

export function LogWithContext(arg1:string,arg2:string,arg3:string,arg4:Record<string, any>):Promise<void>;

export function MoveObjects(arg1:string,arg2:Array<objects.MoveObjectRequest>):Promise<objects.MoveObjectsResult>;

export function MoveObjectsWithOptions(arg1:string,arg2:Array<objects.MoveObjectRequest>,arg3:objects.MutationOptions):Promise<objects.MoveObjectsResult>;

export function OnSecondInstance(arg1:options.SecondInstanceData):Promise<void>;

export function OpenDirectoryDialogWithFiles(arg1:string):Promise<app.DirectoryFilesResult>;

export function OpenFileDialog(arg1:string,arg2:Array<app.FileFilter>):Promise<string>;

export function OpenLogDirectory():Promise<void>;

export function OpenMultipleFilesDialog(arg1:string,arg2:Array<app.FileFilter>):Promise<Array<string>>;

export function PauseTransferTask(arg1:string):Promise<void>;

export function PingEndpoint(arg1:string,arg2:number):Promise<system.PingResult>;

export function ProviderFeatures():Promise<Array<types.ProviderFeature>>;

export function RenameObject(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function RenameObjectWithOptions(arg1:string,arg2:string,arg3:string,arg4:string,arg5:objects.MutationOptions):Promise<void>;

export function ResumeTransferTask(arg1:string):Promise<void>;

export function SaveFileDialog(arg1:string,arg2:string,arg3:Array<app.FileFilter>):Promise<string>;

export function SelectLocalFolder(arg1:string):Promise<string>;

export function SetActiveAccount(arg1:string):Promise<accounts.Account>;

export function SetBucketACL(arg1:string,arg2:string,arg3:storage.BucketACL):Promise<void>;

export function SetBucketCORS(arg1:string,arg2:string,arg3:config.BucketCORS):Promise<void>;

export function SetBucketEncryption(arg1:string,arg2:string,arg3:config.BucketEncryption):Promise<void>;

export function SetBucketLifecycle(arg1:string,arg2:string,arg3:Array<config.LifecycleRule>):Promise<void>;

export function SetBucketPolicy(arg1:string,arg2:string,arg3:config.BucketPolicy):Promise<void>;

export function SetBucketReferer(arg1:string,arg2:string,arg3:storage.BucketReferer):Promise<void>;

export function SetBucketWebsite(arg1:string,arg2:string,arg3:config.BucketWebsite):Promise<void>;

export function SetLogLevel(arg1:string):Promise<void>;

export function SetPublicAccessBlock(arg1:string,arg2:string,arg3:storage.PublicAccessBlock):Promise<void>;

export function SetTransferConcurrency(arg1:number):Promise<void>;

export function SetTransferSpeedLimit(arg1:number):Promise<void>;

export function ShowPathInFileManager(arg1:string):Promise<void>;

export function SupportedProviders():Promise<Array<types.ProviderMetadata>>;

export function SuspendBucketVersioning(arg1:string,arg2:string):Promise<void>;

export function UpdateAccount(arg1:string,arg2:accounts.UpdateAccountInput):Promise<accounts.Account>;

export function UpdateObjectAttributes(arg1:string,arg2:objects.ObjectAttributesPatch):Promise<objects.ObjectAttributes>;

export function UpdateObjectLegalHold(arg1:string,arg2:objects.UpdateObjectLegalHoldInput):Promise<storage.ObjectLegalHoldState>;

export function UpdateObjectRetention(arg1:string,arg2:objects.UpdateObjectRetentionInput):Promise<storage.ObjectRetentionState>;

export function UploadFilesFromPaths(arg1:app.UploadFilesInput):Promise<app.UploadFilesResult>;

export function UploadObject(arg1:string,arg2:string,arg3:string,arg4:string):Promise<transfer.TransferTask>;

export function UploadPart(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:string):Promise<string>;
