/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountsAccountIdTransfersRouteImport } from './routes/accounts/$accountId/transfers'
import { Route as AccountsAccountIdSearchRouteImport } from './routes/accounts/$accountId/search'
import { Route as AccountsAccountIdDashboardRouteImport } from './routes/accounts/$accountId/dashboard'
import { Route as AccountsAccountIdBucketsBucketIdSettingsRouteImport } from './routes/accounts/$accountId/buckets/$bucketId/settings'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsAccountIdTransfersRoute =
  AccountsAccountIdTransfersRouteImport.update({
    id: '/accounts/$accountId/transfers',
    path: '/accounts/$accountId/transfers',
    getParentRoute: () => rootRouteImport,
  } as any)
const AccountsAccountIdSearchRoute = AccountsAccountIdSearchRouteImport.update({
  id: '/accounts/$accountId/search',
  path: '/accounts/$accountId/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsAccountIdDashboardRoute =
  AccountsAccountIdDashboardRouteImport.update({
    id: '/accounts/$accountId/dashboard',
    path: '/accounts/$accountId/dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const AccountsAccountIdBucketsBucketIdSettingsRoute =
  AccountsAccountIdBucketsBucketIdSettingsRouteImport.update({
    id: '/accounts/$accountId/buckets/$bucketId/settings',
    path: '/accounts/$accountId/buckets/$bucketId/settings',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/settings': typeof SettingsRoute
  '/accounts/$accountId/dashboard': typeof AccountsAccountIdDashboardRoute
  '/accounts/$accountId/search': typeof AccountsAccountIdSearchRoute
  '/accounts/$accountId/transfers': typeof AccountsAccountIdTransfersRoute
  '/accounts/$accountId/buckets/$bucketId/settings': typeof AccountsAccountIdBucketsBucketIdSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/settings': typeof SettingsRoute
  '/accounts/$accountId/dashboard': typeof AccountsAccountIdDashboardRoute
  '/accounts/$accountId/search': typeof AccountsAccountIdSearchRoute
  '/accounts/$accountId/transfers': typeof AccountsAccountIdTransfersRoute
  '/accounts/$accountId/buckets/$bucketId/settings': typeof AccountsAccountIdBucketsBucketIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/settings': typeof SettingsRoute
  '/accounts/$accountId/dashboard': typeof AccountsAccountIdDashboardRoute
  '/accounts/$accountId/search': typeof AccountsAccountIdSearchRoute
  '/accounts/$accountId/transfers': typeof AccountsAccountIdTransfersRoute
  '/accounts/$accountId/buckets/$bucketId/settings': typeof AccountsAccountIdBucketsBucketIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/settings'
    | '/accounts/$accountId/dashboard'
    | '/accounts/$accountId/search'
    | '/accounts/$accountId/transfers'
    | '/accounts/$accountId/buckets/$bucketId/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/settings'
    | '/accounts/$accountId/dashboard'
    | '/accounts/$accountId/search'
    | '/accounts/$accountId/transfers'
    | '/accounts/$accountId/buckets/$bucketId/settings'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/settings'
    | '/accounts/$accountId/dashboard'
    | '/accounts/$accountId/search'
    | '/accounts/$accountId/transfers'
    | '/accounts/$accountId/buckets/$bucketId/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  SettingsRoute: typeof SettingsRoute
  AccountsAccountIdDashboardRoute: typeof AccountsAccountIdDashboardRoute
  AccountsAccountIdSearchRoute: typeof AccountsAccountIdSearchRoute
  AccountsAccountIdTransfersRoute: typeof AccountsAccountIdTransfersRoute
  AccountsAccountIdBucketsBucketIdSettingsRoute: typeof AccountsAccountIdBucketsBucketIdSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/$accountId/transfers': {
      id: '/accounts/$accountId/transfers'
      path: '/accounts/$accountId/transfers'
      fullPath: '/accounts/$accountId/transfers'
      preLoaderRoute: typeof AccountsAccountIdTransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/$accountId/search': {
      id: '/accounts/$accountId/search'
      path: '/accounts/$accountId/search'
      fullPath: '/accounts/$accountId/search'
      preLoaderRoute: typeof AccountsAccountIdSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/$accountId/dashboard': {
      id: '/accounts/$accountId/dashboard'
      path: '/accounts/$accountId/dashboard'
      fullPath: '/accounts/$accountId/dashboard'
      preLoaderRoute: typeof AccountsAccountIdDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/$accountId/buckets/$bucketId/settings': {
      id: '/accounts/$accountId/buckets/$bucketId/settings'
      path: '/accounts/$accountId/buckets/$bucketId/settings'
      fullPath: '/accounts/$accountId/buckets/$bucketId/settings'
      preLoaderRoute: typeof AccountsAccountIdBucketsBucketIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  SettingsRoute: SettingsRoute,
  AccountsAccountIdDashboardRoute: AccountsAccountIdDashboardRoute,
  AccountsAccountIdSearchRoute: AccountsAccountIdSearchRoute,
  AccountsAccountIdTransfersRoute: AccountsAccountIdTransfersRoute,
  AccountsAccountIdBucketsBucketIdSettingsRoute:
    AccountsAccountIdBucketsBucketIdSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
