/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransfersRouteImport } from './routes/transfers'
import { Route as SyncRouteImport } from './routes/sync'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MigrationRouteImport } from './routes/migration'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountsAccountIdRouteImport } from './routes/accounts/$accountId'
import { Route as AccountsAccountIdTransfersRouteImport } from './routes/accounts/$accountId/transfers'
import { Route as AccountsAccountIdSecurityRouteImport } from './routes/accounts/$accountId/security'
import { Route as AccountsAccountIdDashboardRouteImport } from './routes/accounts/$accountId/dashboard'
import { Route as AccountsAccountIdBucketsBucketIdSettingsRouteImport } from './routes/accounts/$accountId/buckets/$bucketId/settings'

const TransfersRoute = TransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const SyncRoute = SyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MigrationRoute = MigrationRouteImport.update({
  id: '/migration',
  path: '/migration',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsAccountIdRoute = AccountsAccountIdRouteImport.update({
  id: '/accounts/$accountId',
  path: '/accounts/$accountId',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsAccountIdTransfersRoute =
  AccountsAccountIdTransfersRouteImport.update({
    id: '/transfers',
    path: '/transfers',
    getParentRoute: () => AccountsAccountIdRoute,
  } as any)
const AccountsAccountIdSecurityRoute =
  AccountsAccountIdSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AccountsAccountIdRoute,
  } as any)
const AccountsAccountIdDashboardRoute =
  AccountsAccountIdDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AccountsAccountIdRoute,
  } as any)
const AccountsAccountIdBucketsBucketIdSettingsRoute =
  AccountsAccountIdBucketsBucketIdSettingsRouteImport.update({
    id: '/buckets/$bucketId/settings',
    path: '/buckets/$bucketId/settings',
    getParentRoute: () => AccountsAccountIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/migration': typeof MigrationRoute
  '/settings': typeof SettingsRoute
  '/sync': typeof SyncRoute
  '/transfers': typeof TransfersRoute
  '/accounts/$accountId': typeof AccountsAccountIdRouteWithChildren
  '/accounts/$accountId/dashboard': typeof AccountsAccountIdDashboardRoute
  '/accounts/$accountId/security': typeof AccountsAccountIdSecurityRoute
  '/accounts/$accountId/transfers': typeof AccountsAccountIdTransfersRoute
  '/accounts/$accountId/buckets/$bucketId/settings': typeof AccountsAccountIdBucketsBucketIdSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/migration': typeof MigrationRoute
  '/settings': typeof SettingsRoute
  '/sync': typeof SyncRoute
  '/transfers': typeof TransfersRoute
  '/accounts/$accountId': typeof AccountsAccountIdRouteWithChildren
  '/accounts/$accountId/dashboard': typeof AccountsAccountIdDashboardRoute
  '/accounts/$accountId/security': typeof AccountsAccountIdSecurityRoute
  '/accounts/$accountId/transfers': typeof AccountsAccountIdTransfersRoute
  '/accounts/$accountId/buckets/$bucketId/settings': typeof AccountsAccountIdBucketsBucketIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/migration': typeof MigrationRoute
  '/settings': typeof SettingsRoute
  '/sync': typeof SyncRoute
  '/transfers': typeof TransfersRoute
  '/accounts/$accountId': typeof AccountsAccountIdRouteWithChildren
  '/accounts/$accountId/dashboard': typeof AccountsAccountIdDashboardRoute
  '/accounts/$accountId/security': typeof AccountsAccountIdSecurityRoute
  '/accounts/$accountId/transfers': typeof AccountsAccountIdTransfersRoute
  '/accounts/$accountId/buckets/$bucketId/settings': typeof AccountsAccountIdBucketsBucketIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/migration'
    | '/settings'
    | '/sync'
    | '/transfers'
    | '/accounts/$accountId'
    | '/accounts/$accountId/dashboard'
    | '/accounts/$accountId/security'
    | '/accounts/$accountId/transfers'
    | '/accounts/$accountId/buckets/$bucketId/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/migration'
    | '/settings'
    | '/sync'
    | '/transfers'
    | '/accounts/$accountId'
    | '/accounts/$accountId/dashboard'
    | '/accounts/$accountId/security'
    | '/accounts/$accountId/transfers'
    | '/accounts/$accountId/buckets/$bucketId/settings'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/migration'
    | '/settings'
    | '/sync'
    | '/transfers'
    | '/accounts/$accountId'
    | '/accounts/$accountId/dashboard'
    | '/accounts/$accountId/security'
    | '/accounts/$accountId/transfers'
    | '/accounts/$accountId/buckets/$bucketId/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  MigrationRoute: typeof MigrationRoute
  SettingsRoute: typeof SettingsRoute
  SyncRoute: typeof SyncRoute
  TransfersRoute: typeof TransfersRoute
  AccountsAccountIdRoute: typeof AccountsAccountIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transfers': {
      id: '/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof TransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sync': {
      id: '/sync'
      path: '/sync'
      fullPath: '/sync'
      preLoaderRoute: typeof SyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/migration': {
      id: '/migration'
      path: '/migration'
      fullPath: '/migration'
      preLoaderRoute: typeof MigrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/$accountId': {
      id: '/accounts/$accountId'
      path: '/accounts/$accountId'
      fullPath: '/accounts/$accountId'
      preLoaderRoute: typeof AccountsAccountIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/$accountId/transfers': {
      id: '/accounts/$accountId/transfers'
      path: '/transfers'
      fullPath: '/accounts/$accountId/transfers'
      preLoaderRoute: typeof AccountsAccountIdTransfersRouteImport
      parentRoute: typeof AccountsAccountIdRoute
    }
    '/accounts/$accountId/security': {
      id: '/accounts/$accountId/security'
      path: '/security'
      fullPath: '/accounts/$accountId/security'
      preLoaderRoute: typeof AccountsAccountIdSecurityRouteImport
      parentRoute: typeof AccountsAccountIdRoute
    }
    '/accounts/$accountId/dashboard': {
      id: '/accounts/$accountId/dashboard'
      path: '/dashboard'
      fullPath: '/accounts/$accountId/dashboard'
      preLoaderRoute: typeof AccountsAccountIdDashboardRouteImport
      parentRoute: typeof AccountsAccountIdRoute
    }
    '/accounts/$accountId/buckets/$bucketId/settings': {
      id: '/accounts/$accountId/buckets/$bucketId/settings'
      path: '/buckets/$bucketId/settings'
      fullPath: '/accounts/$accountId/buckets/$bucketId/settings'
      preLoaderRoute: typeof AccountsAccountIdBucketsBucketIdSettingsRouteImport
      parentRoute: typeof AccountsAccountIdRoute
    }
  }
}

interface AccountsAccountIdRouteChildren {
  AccountsAccountIdDashboardRoute: typeof AccountsAccountIdDashboardRoute
  AccountsAccountIdSecurityRoute: typeof AccountsAccountIdSecurityRoute
  AccountsAccountIdTransfersRoute: typeof AccountsAccountIdTransfersRoute
  AccountsAccountIdBucketsBucketIdSettingsRoute: typeof AccountsAccountIdBucketsBucketIdSettingsRoute
}

const AccountsAccountIdRouteChildren: AccountsAccountIdRouteChildren = {
  AccountsAccountIdDashboardRoute: AccountsAccountIdDashboardRoute,
  AccountsAccountIdSecurityRoute: AccountsAccountIdSecurityRoute,
  AccountsAccountIdTransfersRoute: AccountsAccountIdTransfersRoute,
  AccountsAccountIdBucketsBucketIdSettingsRoute:
    AccountsAccountIdBucketsBucketIdSettingsRoute,
}

const AccountsAccountIdRouteWithChildren =
  AccountsAccountIdRoute._addFileChildren(AccountsAccountIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  MigrationRoute: MigrationRoute,
  SettingsRoute: SettingsRoute,
  SyncRoute: SyncRoute,
  TransfersRoute: TransfersRoute,
  AccountsAccountIdRoute: AccountsAccountIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
