// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {accounts} from '../models';
import {objects} from '../models';
import {buckets} from '../models';
import {transfer} from '../models';
import {types} from '../models';

export function AbortMultipartUpload(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function ActiveAccount():Promise<accounts.Account>;

export function BucketLocation(arg1:string,arg2:string):Promise<string>;

export function CancelTransferTask(arg1:string):Promise<void>;

export function CompleteMultipartUpload(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Record<number, string>):Promise<void>;

export function CopyObject(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function CreateAccount(arg1:accounts.CreateAccountInput):Promise<accounts.Account>;

export function CreateBucket(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteAccount(arg1:string):Promise<void>;

export function DeleteBucket(arg1:string,arg2:string):Promise<void>;

export function DeleteObject(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DownloadObject(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function ExportAccounts():Promise<accounts.ExportSummary>;

export function GetPresignedDownloadURL(arg1:string,arg2:string,arg3:string,arg4:number):Promise<string>;

export function GetPresignedUploadURL(arg1:string,arg2:string,arg3:string,arg4:number):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function HeadBucket(arg1:string,arg2:string):Promise<void>;

export function HeadObject(arg1:string,arg2:string,arg3:string):Promise<objects.ObjectInfo>;

export function ImportAccounts():Promise<accounts.ImportSummary>;

export function InitiateMultipartUpload(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ListAccounts():Promise<Array<accounts.Account>>;

export function ListBuckets(arg1:string):Promise<Array<buckets.BucketInfo>>;

export function ListObjects(arg1:string,arg2:objects.ListObjectsInput):Promise<objects.ListObjectsResult>;

export function ListTransferTasks():Promise<Array<transfer.TransferTask>>;

export function PauseTransferTask(arg1:string):Promise<void>;

export function ProviderCapabilities():Promise<Array<types.ProviderCapability>>;

export function ResumeTransferTask(arg1:string):Promise<void>;

export function SetActiveAccount(arg1:string):Promise<accounts.Account>;

export function SupportedProviders():Promise<Array<types.ProviderMetadata>>;

export function TestAccountConnection(arg1:string):Promise<accounts.ConnectionTestResult>;

export function UpdateAccount(arg1:string,arg2:accounts.UpdateAccountInput):Promise<accounts.Account>;

export function UploadObject(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UploadPart(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:Array<number>):Promise<string>;
