// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {accounts} from '../models';
import {types} from '../models';

export function ActiveAccount():Promise<accounts.Account>;

export function CreateAccount(arg1:accounts.CreateAccountInput):Promise<accounts.Account>;

export function DeleteAccount(arg1:string):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function ListAccounts():Promise<Array<accounts.Account>>;

export function SetActiveAccount(arg1:string):Promise<accounts.Account>;

export function SupportedProviders():Promise<Array<types.ProviderMetadata>>;

export function TestAccountConnection(arg1:string):Promise<accounts.ConnectionTestResult>;

export function UpdateAccount(arg1:string,arg2:accounts.UpdateAccountInput):Promise<accounts.Account>;
