// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbortMultipartUpload(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AbortMultipartUpload'](arg1, arg2, arg3, arg4);
}

export function ActiveAccount() {
  return window['go']['main']['App']['ActiveAccount']();
}

export function BucketLocation(arg1, arg2) {
  return window['go']['main']['App']['BucketLocation'](arg1, arg2);
}

export function CancelTransferTask(arg1) {
  return window['go']['main']['App']['CancelTransferTask'](arg1);
}

export function CompleteMultipartUpload(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CompleteMultipartUpload'](arg1, arg2, arg3, arg4, arg5);
}

export function CopyObject(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CopyObject'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateAccount(arg1) {
  return window['go']['main']['App']['CreateAccount'](arg1);
}

export function CreateBucket(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateBucket'](arg1, arg2, arg3);
}

export function DeleteAccount(arg1) {
  return window['go']['main']['App']['DeleteAccount'](arg1);
}

export function DeleteBucket(arg1, arg2) {
  return window['go']['main']['App']['DeleteBucket'](arg1, arg2);
}

export function DeleteObject(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteObject'](arg1, arg2, arg3);
}

export function DownloadObject(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DownloadObject'](arg1, arg2, arg3, arg4);
}

export function ExportAccounts() {
  return window['go']['main']['App']['ExportAccounts']();
}

export function GetPresignedDownloadURL(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetPresignedDownloadURL'](arg1, arg2, arg3, arg4);
}

export function GetPresignedUploadURL(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetPresignedUploadURL'](arg1, arg2, arg3, arg4);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HeadBucket(arg1, arg2) {
  return window['go']['main']['App']['HeadBucket'](arg1, arg2);
}

export function HeadObject(arg1, arg2, arg3) {
  return window['go']['main']['App']['HeadObject'](arg1, arg2, arg3);
}

export function ImportAccounts() {
  return window['go']['main']['App']['ImportAccounts']();
}

export function InitiateMultipartUpload(arg1, arg2, arg3) {
  return window['go']['main']['App']['InitiateMultipartUpload'](arg1, arg2, arg3);
}

export function ListAccounts() {
  return window['go']['main']['App']['ListAccounts']();
}

export function ListBuckets(arg1) {
  return window['go']['main']['App']['ListBuckets'](arg1);
}

export function ListObjects(arg1, arg2) {
  return window['go']['main']['App']['ListObjects'](arg1, arg2);
}

export function ListTransferTasks() {
  return window['go']['main']['App']['ListTransferTasks']();
}

export function PauseTransferTask(arg1) {
  return window['go']['main']['App']['PauseTransferTask'](arg1);
}

export function ProviderCapabilities() {
  return window['go']['main']['App']['ProviderCapabilities']();
}

export function ResumeTransferTask(arg1) {
  return window['go']['main']['App']['ResumeTransferTask'](arg1);
}

export function SetActiveAccount(arg1) {
  return window['go']['main']['App']['SetActiveAccount'](arg1);
}

export function SupportedProviders() {
  return window['go']['main']['App']['SupportedProviders']();
}

export function TestAccountConnection(arg1) {
  return window['go']['main']['App']['TestAccountConnection'](arg1);
}

export function UpdateAccount(arg1, arg2) {
  return window['go']['main']['App']['UpdateAccount'](arg1, arg2);
}

export function UploadObject(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UploadObject'](arg1, arg2, arg3, arg4);
}

export function UploadPart(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UploadPart'](arg1, arg2, arg3, arg4, arg5, arg6);
}
