// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {accounts} from '../models';
import {backup} from '../models';
import {migration} from '../models';
import {transfer} from '../models';
import {search} from '../models';
import {analytics} from '../models';
import {config} from '../models';
import {system} from '../models';
import {objects} from '../models';
import {buckets} from '../models';
import {types} from '../models';

export function AbortMultipartUpload(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function ActiveAccount():Promise<accounts.Account>;

export function BucketLocation(arg1:string,arg2:string):Promise<string>;

export function CancelMigrationJob(arg1:string):Promise<void>;

export function CancelTransferTask(arg1:string):Promise<void>;

export function CompleteMultipartUpload(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Record<number, string>):Promise<void>;

export function CopyObject(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function CreateAccount(arg1:accounts.CreateAccountInput):Promise<accounts.Account>;

export function CreateAppBackup(arg1:boolean,arg2:string):Promise<backup.BackupHeader>;

export function CreateBucket(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CreateBucketSnapshot(arg1:string,arg2:string):Promise<backup.BackupHeader>;

export function CreateMigrationJob(arg1:migration.EndpointInfo,arg2:migration.EndpointInfo,arg3:migration.MigrationOptions):Promise<migration.MigrationJob>;

export function DeleteAccount(arg1:string):Promise<void>;

export function DeleteBucket(arg1:string,arg2:string):Promise<void>;

export function DeleteBucketCORS(arg1:string,arg2:string):Promise<void>;

export function DeleteBucketEncryption(arg1:string,arg2:string):Promise<void>;

export function DeleteBucketLifecycle(arg1:string,arg2:string):Promise<void>;

export function DeleteBucketPolicy(arg1:string,arg2:string):Promise<void>;

export function DeleteBucketWebsite(arg1:string,arg2:string):Promise<void>;

export function DeleteObject(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteSavedSearchQuery(arg1:string):Promise<void>;

export function DownloadObject(arg1:string,arg2:string,arg3:string,arg4:string):Promise<transfer.TransferTask>;

export function EnableBucketVersioning(arg1:string,arg2:string):Promise<void>;

export function ExportAccounts():Promise<accounts.ExportSummary>;

export function ExportSearchResults(arg1:string,arg2:search.SearchQuery,arg3:string):Promise<Array<number>>;

export function GetAnalyticsSummary(arg1:string):Promise<analytics.AnalyticsSummary>;

export function GetBucketCORS(arg1:string,arg2:string):Promise<config.BucketCORS>;

export function GetBucketEncryption(arg1:string,arg2:string):Promise<config.BucketEncryption>;

export function GetBucketLifecycle(arg1:string,arg2:string):Promise<Array<config.LifecycleRule>>;

export function GetBucketPolicy(arg1:string,arg2:string):Promise<config.BucketPolicy>;

export function GetBucketVersioning(arg1:string,arg2:string):Promise<config.BucketVersioning>;

export function GetBucketWebsite(arg1:string,arg2:string):Promise<config.BucketWebsite>;

export function GetMigrationJob(arg1:string):Promise<migration.MigrationJob>;

export function GetPresignedDownloadURL(arg1:string,arg2:string,arg3:string,arg4:number):Promise<string>;

export function GetPresignedUploadURL(arg1:string,arg2:string,arg3:string,arg4:number):Promise<string>;

export function GetSystemMetrics():Promise<system.SystemMetrics>;

export function GetTransferSpeedLimit():Promise<number>;

export function Greet(arg1:string):Promise<string>;

export function HeadBucket(arg1:string,arg2:string):Promise<void>;

export function HeadObject(arg1:string,arg2:string,arg3:string):Promise<objects.ObjectInfo>;

export function ImportAccounts():Promise<accounts.ImportSummary>;

export function InitiateMultipartUpload(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ListAccounts():Promise<Array<accounts.Account>>;

export function ListBuckets(arg1:string):Promise<Array<buckets.BucketInfo>>;

export function ListMigrationJobs():Promise<Array<migration.MigrationJob>>;

export function ListObjects(arg1:string,arg2:objects.ListObjectsInput):Promise<objects.ListObjectsResult>;

export function ListSavedSearchQueries():Promise<Array<search.SavedQuery>>;

export function ListTransferTasks():Promise<Array<transfer.TransferTask>>;

export function PauseMigrationJob(arg1:string):Promise<void>;

export function PauseTransferTask(arg1:string):Promise<void>;

export function ProviderCapabilities():Promise<Array<types.ProviderCapability>>;

export function RenameObject(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function RestoreAppBackup():Promise<void>;

export function ResumeTransferTask(arg1:string):Promise<void>;

export function SaveSearchQuery(arg1:string,arg2:search.SearchQuery):Promise<search.SavedQuery>;

export function SearchObjects(arg1:string,arg2:search.SearchQuery):Promise<search.SearchResponse>;

export function SetActiveAccount(arg1:string):Promise<accounts.Account>;

export function SetBucketCORS(arg1:string,arg2:string,arg3:config.BucketCORS):Promise<void>;

export function SetBucketEncryption(arg1:string,arg2:string,arg3:config.BucketEncryption):Promise<void>;

export function SetBucketLifecycle(arg1:string,arg2:string,arg3:Array<config.LifecycleRule>):Promise<void>;

export function SetBucketPolicy(arg1:string,arg2:string,arg3:config.BucketPolicy):Promise<void>;

export function SetBucketWebsite(arg1:string,arg2:string,arg3:config.BucketWebsite):Promise<void>;

export function SetTransferSpeedLimit(arg1:number):Promise<void>;

export function StartMigrationJob(arg1:string):Promise<void>;

export function SupportedProviders():Promise<Array<types.ProviderMetadata>>;

export function SuspendBucketVersioning(arg1:string,arg2:string):Promise<void>;

export function TestAccountConnection(arg1:string):Promise<accounts.ConnectionTestResult>;

export function TestAccountConnectionPreview(arg1:accounts.CreateAccountInput):Promise<accounts.ConnectionTestResult>;

export function UpdateAccount(arg1:string,arg2:accounts.UpdateAccountInput):Promise<accounts.Account>;

export function UpdateSavedSearchQuery(arg1:string,arg2:string,arg3:search.SearchQuery):Promise<search.SavedQuery>;

export function UploadObject(arg1:string,arg2:string,arg3:string,arg4:string):Promise<transfer.TransferTask>;

export function UploadPart(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:Array<number>):Promise<string>;
